# Generated by Django 5.0.3 on 2024-08-01 16:47

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="title",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog", verbose_name="image"
                    ),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="text")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publish date"
                    ),
                ),
            ],
            options={
                "verbose_name": "blog post",
                "verbose_name_plural": "blog posts",
                "ordering": ["pub_date"],
            },
        ),
    ]
