# Generated by Django 4.0.8 on 2022-11-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendarOf",
                to="calendars.calendar",
            ),
        ),
    ]
