# Generated by Django 5.0.3 on 2024-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0005_alter_calendar_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="include_source",
            field=models.BooleanField(
                default=False, help_text="Include source name in event title"
            ),
        ),
    ]
