# Generated by Django 5.0.3 on 2024-04-28 13:37

import mergecal.calendars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0006_calendar_include_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(
                max_length=400, validators=[mergecal.calendars.models.validate_ical_url]
            ),
        ),
    ]
