# Generated by Django 5.0.3 on 2024-08-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calendars",
            "0009_calendar_created_calendar_modified_source_created_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="custom_prefix",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="source",
            name="exclude_keywords",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of keywords to exclude events",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="include_description",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="source",
            name="include_location",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="source",
            name="include_title",
            field=models.BooleanField(default=True),
        ),
    ]
