# Generated by Django 4.1.3 on 2022-11-23 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0002_alter_source_calendar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendar",
            options={"ordering": ["-pk"]},
        ),
    ]
