# Generated by Django 4.1.3 on 2022-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0003_alter_calendar_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendar",
            name="calendar_file",
        ),
        migrations.AddField(
            model_name="calendar",
            name="calendar_file_str",
            field=models.TextField(blank=True, null=True),
        ),
    ]
