# Generated by Django 5.0.3 on 2024-08-01 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0008_calendar_remove_branding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calendar",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="source",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
