# Generated by Django 5.0.3 on 2025-01-26 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0011_remove_calendar_calendar_file_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
