# Generated by Django 5.0.3 on 2024-07-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("elite", "Elite"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
