# Generated by Django 5.0.3 on 2024-07-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_subscription_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("free_tier", "Free Tier"),
                    ("personal_tier", "Personal Tier"),
                    ("buisness_tier", "Business Tier"),
                    ("supporter_tier", "Supporter Tier"),
                ],
                default="free_tier",
                max_length=14,
            ),
        ),
    ]
