# Generated by Django 5.0.11 on 2025-02-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0012_alter_calendar_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalnedarSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('google_calendar_id', models.CharField(help_text='ID of the synchronized Google Calendar', max_length=255)),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last time this calendar was synchronized', null=True)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to='calendars.calendar')),
            ],
            options={
                'verbose_name': 'Google Calendar Sync',
                'verbose_name_plural': 'Google Calendar Syncs',
                'abstract': False,
            },
        ),
    ]
