# Generated by Django 5.0.11 on 2025-02-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0012_alter_calendar_uuid'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleCalnedarSync',
            new_name='GoogleCalendarSync',
        ),
    ]
